### ISSUE TITLE
CodeClimate is not working

### ISSUE THREAD

**Issue by sobrinho** [standardrb/standard#439]
Isn't this plugin working anymore?

Running the standard in my project I can see the errors but CodeClimate isn't reporting anything:

<img width="1194" alt="Screen Shot 2022-07-19 at 18 03 28" src="https://user-images.githubusercontent.com/26460/179848016-88af2983-4a52-4320-bc57-b9af3072c08d.png">

cc @jakeonfire

**Comment by searls** [comment]
Great question! I don't think I've used the plugin myself. It looks like it's passing in your screenshot, should it have failed?

**Comment by jakeonfire** [comment]
fwiw the plugin is hosted here: https://github.com/jakeonfire/codeclimate-standard, though @codeclimate manages the releases. it still works for us. there is no output from standard in that view ever. codeclimate will only scan files with changes and then only show you issues for code which you've changed. you can try the `beta` release (i'm not sure if it's different or not though).
```yaml
version: "2"
plugins:
  standard:
    enabled: true
    channel: beta
```

**Comment by sobrinho** [comment]
BTW, I tried to use the rubocop plugin alone and also together with the standard plugin but then it complains that the YAML from the gem couldn't be found, I'm guessing that's not how CodeClimate works (pulling my Gemfile somehow).

Which also makes me wonder, how the plugin knows the standard version I'm using in my project? Does it know at all?

**Comment by jakeonfire** [comment]
the plugin has its own [Gemfile](https://github.com/jakeonfire/codeclimate-standard/blob/master/Gemfile) and [Gemfile.lock](https://github.com/jakeonfire/codeclimate-standard/blob/master/Gemfile.lock) so it's using 1.4.0 - a bit behind.

we are successfully using both `rubocop` and `standard`:
```yaml
version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-18-3
  standard:
    enabled: true
    channel: beta
```

not sure what you mean by
> it complains that the YAML from the gem couldn't be found
