### ISSUE TITLE
Zed editor using default rubocop settings

### ISSUE THREAD

**Issue by LucasKuhn** [standardrb/standard#608]
When using Zed editor, the installation of standard for some reason is picking up only the default rubocop configuration:
![image](https://github.com/standardrb/standard/assets/26127185/3f3762ec-96c6-4675-aea5-d2702f7a78c5)
What I believe is happening, is that bundle installs rubocop, and Zed is only using vanilla rubocop.  

As a temporary workaround I'm using the [base](https://github.com/standardrb/standard/blob/main/config/base.yml) config to be my [default rubocop configuration](https://docs.rubocop.org/rubocop/configuration.html#config-file-locations) by adding the rules to `~/.rubocop.yml` :
![image](https://github.com/standardrb/standard/assets/26127185/05eee7bc-b8ae-4c95-b6f5-dcfb325c9b55)
Which is not ideal. If anyone manages to get it working properly on Zed, please follow up

**Comment by Otterpocket** [comment]
@LucasKuhn I didn't know you could even get Zed to display inline standardrb hints, I tried and failed, even using the workaround. Could share your Zed config please?

**Comment by LucasKuhn** [comment]
Did you run bundle install after adding the gems you need to have rubocop installed for the inline hints to work with rubocop? 
The inline hints come from the ruby LSP already provided by Zed, Solargraph ( https://github.com/zed-industries/zed/blob/main/docs/src/languages/ruby.md ) 
This is my `~/.config/zed` 
```js
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  // "format_on_save": "off",
  "vim_mode": false,
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "lsp": {
    "solargraph": {
      "initialization_options": {
        "diagnostics": true,
        "formatting": true
      }
    }
  },
  "language_overrides": {
    "ERB": {
      "formatter": {
        "external": {
          "command": "erb-format",
          "arguments": ["--stdin", "--print-width", "120"]
        }
      }
    }
  }
}
```
And this is what I'm currently using on my project's `.rubocob.yml`
```yml
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

AllCops:
  Exclude:
    - "**/*.erb"
  SuggestExtensions: false
```
