### ISSUE TITLE
`extend_config` no longer working with Rubocop 1.72 plugin

### ISSUE THREAD

**Issue by darronschall** [standardrb/standard#701]
I have a project using standard with an `extend_config` to pull in [rubocop-rspec](https://github.com/rubocop/rubocop-rspec). My config is simple:

```yml
# .standard.yml
plugins:
  - standard-performance
  - standard-rails

extend_config:
  - .rubocop_rspec.yml
```

```yml
# rubocop_rspec.yml
require:
  - rubocop-rspec

# Easier to read than "is_expected.to"
RSpec/ImplicitExpect:
  EnforcedStyle: should

# Can't always provide meaningful names, especially when testing collections
RSpec/IndexedLet:
  Max: 3
```

This was working great up until the [rubocop-rspec 3.5.0](https://github.com/rubocop/rubocop-rspec/releases/tag/v3.5.0) release, when the gem was changed to a [Rubocop 1.72 plugin](https://docs.rubocop.org/rubocop/plugin_migration_guide.html). 

I am no longer able to extend the default configuration of rubocop-rspec. For now I've pinned the gem to 3.4.0, but I'd like to be able to upgrade at some point.

I'm wondering if this is failing for the same reason in the comment at https://github.com/standardrb/standard/issues/540#issuecomment-1474292307, and if `extend_config` needs some changes, especially as more rubocop extensions migrate towards the plugin approach...
