### ISSUE TITLE
migrate to plugin support

### ISSUE THREAD

**Issue by alec-c4** [standardrb/standard#704]
Hi!
I have the following config in my `.rubocop` config

```yaml
require:
  - standard

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-factory_bot
  - rubocop-capybara
```

but to use standard as a plugin, I'd like to ask you to add plugin support https://docs.rubocop.org/rubocop/plugin_migration_guide.html
