### ISSUE TITLE
Strip frozen strings comments on Ruby 3.4+

### ISSUE THREAD

**Issue by wfarr** [standardrb/standard#717]
Recently this came up in one of our projects and since we cannot override default standard rules altogether, I figured I'd raise this discussion prior to doing the work.

As of Ruby 3.4, [strings are frozen by default](https://blog.saeloun.com/2024/05/20/frozen-string-literal/). While I'm definitely sympathetic to the concerns raised in #22, especially in versions of Ruby where strings were not frozen by default, in the original thread it was even noted that disabling this style in standard might be a "until it's the default" type setting.

So I guess what I'm proposing is roughly:

```yaml
# config/ruby-3.4.yml
inherit_from: ./base.yml

AllCops:
  TargetRubyVersion: 3.4

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
```
